apiVersion: v1
kind: Service

metadata:
  name: autenticacao-api-service
  namespace: ecociente

spec:
  selector:
    app: autenticacao-api

  ports:
    - protocol: TCP
      port: 9801
      targetPort: 9801

  type: ClusterIP