apiVersion: v1
kind: ConfigMap

metadata:
  name: ecociente-config
  namespace: ecociente

data:
  DB_URL: "jdbc:postgresql://postgres-service:5432/ecociente"

  PORT: "9801"

  DDL_AUTO: "update"
  SHOW_SQL: "false"
  SQL_INIT_MODE: "never"

  JWT_EXPIRATION_MINUTES: "120"