apiVersion: v1
kind: Secret

metadata:
  name: ecociente-secret
  namespace: ecociente

type: Opaque

stringData:
  POSTGRES_DB: "ecociente"

  POSTGRES_USER: "SEU_USUARIO_POSTGRES"
  POSTGRES_PASSWORD: "SUA_SENHA_POSTGRES"

  DB_USERNAME: "SEU_USUARIO_POSTGRES"
  DB_PASSWORD: "SUA_SENHA_POSTGRES"

  JWT_SECRET: "SUA_CHAVE_JWT_COM_PELO_MENOS_32_CARACTERES"