apiVersion: v1
kind: Secret

metadata:
  name: ecociente-secret
  namespace: ecociente

type: Opaque

stringData:
  POSTGRES_DB: "ecociente"

  POSTGRES_USER: "ecociente"
  POSTGRES_PASSWORD: "ALTERE_PARA_UMA_SENHA_LOCAL"

  DB_USERNAME: "ecociente"
  DB_PASSWORD: "ALTERE_PARA_A_MESMA_SENHA_LOCAL"

  JWT_SECRET: "ALTERE_PARA_UMA_CHAVE_COM_PELO_MENOS_32_CARACTERES"